version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-init.sh:/ollama-init.sh
    environment:
      - OLLAMA_MODEL=llama3.2:latest
    entrypoint: ["/bin/bash", "/ollama-init.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list", "|", "grep", "llama3.2"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  rag-service:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - model-cache:/root/.cache
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model-cache:
  ollama-data:
