apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      initContainers:
      - name: wait-for-ollama
        image: busybox:latest
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for Ollama to be ready..."
          until wget -q -O- http://ollama-service:11434/api/tags 2>/dev/null | grep -q llama3.2; do
            echo "Ollama not ready yet, waiting..."
            sleep 5
          done
          echo "Ollama is ready!"
      containers:
      - name: rag-service
        image: it-knowledge-retrieval-service-rag-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        envFrom:
        - configMapRef:
            name: rag-config
        - secretRef:
            name: rag-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
