apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: rag-system
spec:
  selector:
    app: rag-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
